### ISSUE TITLE
This does not work with recent xen

### ISSUE THREAD

**Issue by mseri** [xapi-project/ocaml-xen-lowlevel-libs#106]
Installing it on a ubuntu 17.10 fails with multiple gcc warning/errors

**Comment by gaborigloi** [comment]
Same on Fedora 27 :(

**Comment by gaborigloi** [comment]
Still does not work on Fedora 27 :( 
```
+ /root/.opam/4.04.2/bin/ocamlfind ocamlc -g -ccopt -Wno-unused-function -ccopt -g -ccopt -ggdb -ccopt -Wno-format-truncation -c xenlight/xenlight_stubs.c
In file included from xenlight/xenlight_stubs.c:420:0:
xenlight/caml_types.h: In function ‘domain_build_info_val’:
xenlight/caml_types.h:1968:24: error: ‘struct <anonymous>’ has no member named ‘mca_caps’
            c_val->u.hvm.mca_caps = Int64_val(Field(Field(Field(v, 40), 0), 44));
                        ^
xenlight/caml_types.h: In function ‘Val_domain_build_info’:
xenlight/caml_types.h:2313:68: error: ‘struct <anonymous>’ has no member named ‘mca_caps’
             anon_field = caml_copy_int64(domain_build_info_c->u.hvm.mca_caps);
                                                                    ^
```

**Comment by mseri** [comment]
This is getting out of control. We need to find a different way of dealing with it

**Comment by gaborigloi** [comment]
Once we get things to work with `4.06`, we can just use `xenctrl.dummy` with the system xenctrl package on Fedora and things should work :)

**Comment by gaborigloi** [comment]
Now it doesn't work on Debian 9 Stretch either, with xen 4.8 :(
